/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlimecodeModoLanRouteImport } from './routes/slimecodeModoLan'
import { Route as IndexRouteImport } from './routes/index'

const SlimecodeModoLanRoute = SlimecodeModoLanRouteImport.update({
  id: '/slimecodeModoLan',
  path: '/slimecodeModoLan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slimecodeModoLan': typeof SlimecodeModoLanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/slimecodeModoLan': typeof SlimecodeModoLanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slimecodeModoLan': typeof SlimecodeModoLanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/slimecodeModoLan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/slimecodeModoLan'
  id: '__root__' | '/' | '/slimecodeModoLan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlimecodeModoLanRoute: typeof SlimecodeModoLanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slimecodeModoLan': {
      id: '/slimecodeModoLan'
      path: '/slimecodeModoLan'
      fullPath: '/slimecodeModoLan'
      preLoaderRoute: typeof SlimecodeModoLanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlimecodeModoLanRoute: SlimecodeModoLanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
